#!/usr/bin/env python3
import os
import requests
import math
from collections import defaultdict, OrderedDict
from datetime import datetime

GITHUB_API = "https://api.github.com"
USERNAME = os.environ.get("GH_USERNAME", "gd0810")
TOKEN = os.environ.get("GITHUB_TOKEN")  # provided by Actions

HEADERS = {"Accept": "application/vnd.github.v3+json"}
if TOKEN:
    HEADERS["Authorization"] = f"token {TOKEN}"

def list_repos(user):
    repos = []
    page = 1
    per_page = 100
    while True:
        url = f"{GITHUB_API}/users/{user}/repos"
        resp = requests.get(url, params={"per_page": per_page, "page": page}, headers=HEADERS, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        if not data:
            break
        repos.extend(data)
        if len(data) < per_page:
            break
        page += 1
    return repos

def repo_languages(owner, repo):
    url = f"{GITHUB_API}/repos/{owner}/{repo}/languages"
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    return resp.json()  # {language: bytes}

def aggregate_languages(repos, owner):
    totals = defaultdict(int)
    for r in repos:
        # skip forks and archived repos
        if r.get("fork") or r.get("archived"):
            continue
        name = r.get("name")
        try:
            langs = repo_languages(owner, name)
        except Exception as e:
            print(f"Warning: failed to fetch languages for {name}: {e}")
            continue
        for lang, bytes_count in langs.items():
            totals[lang] += bytes_count
    return totals

def make_svg(sorted_langs, total_bytes, created_at=None):
    # Basic visual parameters
    width = 900
    left_pad = 20
    right_pad = 20
    bar_max_width = width - left_pad - right_pad - 220  # room for labels
    row_height = 28
    gap = 8
    top_pad = 28
    bottom_pad = 40
    rows = len(sorted_langs)
    height = top_pad + bottom_pad + rows * (row_height + gap)

    # color palette (repeating)
    palette = [
        "#1f77b4","#ff7f0e","#2ca02c","#d62728","#9467bd","#8c564b",
        "#e377c2","#7f7f7f","#bcbd22","#17becf"
    ]

    svg = []
    svg.append(f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">')
    svg.append('<style>')
    svg.append('.label{font: 12px system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial;}')
    svg.append('.lang{font-weight:700;}')
    svg.append('.small{font-size:11px;fill:#6b7280;}')
    svg.append('</style>')

    title = "Most used languages (aggregated)"
    if created_at:
        title += f" — updated {created_at}"
    svg.append(f'<text x="{left_pad}" y="18" class="label lang">{title}</text>')

    y = top_pad
    color_idx = 0
    for lang, count in sorted_langs.items():
        pct = (count / total_bytes * 100) if total_bytes else 0
        bar_w = int((count / total_bytes) * bar_max_width) if total_bytes else 0
        color = palette[color_idx % len(palette)]
        svg.append(f'<text x="{left_pad}" y="{y+16}" class="label">{lang}</text>')
        # percentage text on right side
        pct_text = f"{pct:.1f}%"
        svg.append(f'<text x="{width - right_pad - 50}" y="{y+16}" class="label small">{pct_text}</text>')
        # bar background
        bar_x = left_pad + 140
        svg.append(f'<rect x="{bar_x}" y="{y+4}" width="{bar_max_width}" height="18" rx="6" fill="#f3f4f6"/>')
        # bar foreground
        if bar_w > 0:
            svg.append(f'<rect x="{bar_x}" y="{y+4}" width="{bar_w}" height="18" rx="6" fill="{color}"/>')
        y += row_height + gap
        color_idx += 1

    # footer total
    svg.append(f'<text x="{left_pad}" y="{height - 12}" class="label small">Total bytes: {total_bytes:,} — generated by GitHub Action</text>')
    svg.append('</svg>')
    return "\n".join(svg)

def main():
    print(f"Listing repos for user: {USERNAME}")
    repos = list_repos(USERNAME)
    print(f"Found {len(repos)} repos.")
    totals = aggregate_languages(repos, USERNAME)
    if not totals:
        print("No language data found. Exiting.")
        return
    # sort by bytes desc
    ordered = OrderedDict(sorted(totals.items(), key=lambda kv: kv[1], reverse=True))
    total_bytes = sum(ordered.values())

    # optionally collapse very small languages into 'Other' (keep top 12)
    TOP_N = 12
    top_items = list(ordered.items())[:TOP_N]
    other_items = list(ordered.items())[TOP_N:]
    if other_items:
        other_sum = sum(v for _, v in other_items)
        top_items.append(("Other", other_sum))

    sorted_langs = OrderedDict(top_items)
    created_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    svg = make_svg(sorted_langs, total_bytes, created_at)
    out_path = "languages.svg"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(svg)
    print(f"Wrote {out_path}")

if __name__ == "__main__":
    main()
